/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FileMetadata {
    size: bigint;
    fileBlob: ExternalBlob;
    mimeType: string;
    filename: string;
}
export type UploadError = {
    __kind__: "fileTooLarge";
    fileTooLarge: string;
} | {
    __kind__: "internalError";
    internalError: string;
} | {
    __kind__: "actorUnavailable";
    actorUnavailable: string;
} | {
    __kind__: "callerNotAuthenticated";
    callerNotAuthenticated: string;
};
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface MarketplaceListing {
    id: string;
    title: string;
    sellerWhatsapp: string;
    active: boolean;
    subject: string;
    listingId: string;
    createdBy: Principal;
    sold: boolean;
    sellerName: string;
    buyerPrincipal?: Principal;
    photo: FileMetadata;
    price: bigint;
    classYear: string;
}
export interface ListingUpdate {
    title: string;
    sellerWhatsapp: string;
    subject: string;
    sellerName: string;
    photo: FileMetadata;
    price: bigint;
    classYear: string;
}
export interface ServiceListing {
    id: string;
    active: boolean;
    listingId: string;
    createdBy: Principal;
    serviceDescription: string;
    category: string;
    helperWhatsapp: string;
    helperName: string;
}
export interface Notification {
    listingId: string;
    listingType: ListingType;
    message: string;
    timestamp: bigint;
    listingTitle: string;
}
export interface Paper {
    id: string;
    title: string;
    subject: string;
    year: bigint;
    description: string;
    fileMetadata: FileMetadata;
    uploadedAt: bigint;
    uploadedBy: Principal;
}
export interface UserProfile {
    bio: string;
    displayName: string;
    whatsappNumber: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ListingType {
    service = "service",
    marketplace = "marketplace"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    confirmExchange(listingId: string): Promise<void>;
    createMarketplaceListing(title: string, price: bigint, subject: string, classYear: string, photo: FileMetadata, sellerName: string, sellerWhatsapp: string): Promise<void>;
    createMeetup(listingId: string, meetupNote: string): Promise<void>;
    createRating(listingId: string, rating: number, comment: string | null): Promise<void>;
    createServiceListing(serviceDescription: string, category: string, helperName: string, helperWhatsapp: string): Promise<void>;
    deletePaper(id: string): Promise<void>;
    getActiveMarketplaceListings(): Promise<Array<MarketplaceListing>>;
    getActiveServiceListings(): Promise<Array<ServiceListing>>;
    getAllMarketplaceListingsAdmin(): Promise<Array<MarketplaceListing>>;
    getAllServiceListingsAdmin(): Promise<Array<ServiceListing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getListingRatingSummary(listingId: string): Promise<[number, bigint]>;
    getMarketplaceListingById(listingId: string): Promise<MarketplaceListing | null>;
    getMeetupStatus(listingId: string): Promise<{
        buyerConfirmed: boolean;
        exchangeConfirmed: boolean;
        sellerConfirmed: boolean;
        meetupNote: string;
    }>;
    getMyListings(): Promise<{
        marketplace: Array<MarketplaceListing>;
        services: Array<ServiceListing>;
    }>;
    getPaper(id: string): Promise<Paper | null>;
    getPapers(): Promise<Array<Paper>>;
    getRecentNotifications(): Promise<Array<Notification>>;
    getServiceListingById(listingId: string): Promise<ServiceListing | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markAsPurchased(listingId: string): Promise<void>;
    markNotificationsRead(upTo: bigint): Promise<void>;
    resetPurchaseStatus(listingId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    softDeleteMarketplaceListing(listingId: string): Promise<void>;
    softDeleteServiceListing(listingId: string): Promise<void>;
    updateMarketplaceListing(listingId: string, updateData: ListingUpdate): Promise<void>;
    updateMyProfile(displayName: string, whatsappNumber: string, bio: string): Promise<void>;
    updateServiceListing(listingId: string, updateData: {
        serviceDescription: string;
        category: string;
        helperWhatsapp: string;
        helperName: string;
    }): Promise<void>;
    uploadFile(filename: string, mimeType: string, size: bigint, blob: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: FileMetadata;
    } | {
        __kind__: "err";
        err: UploadError;
    }>;
    uploadPaper(id: string, title: string, subject: string, year: bigint, description: string, fileMetadata: FileMetadata): Promise<void>;
}
import type { ExternalBlob as _ExternalBlob, FileMetadata as _FileMetadata, ListingType as _ListingType, ListingUpdate as _ListingUpdate, MarketplaceListing as _MarketplaceListing, Notification as _Notification, Paper as _Paper, ServiceListing as _ServiceListing, UploadError as _UploadError, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmExchange(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmExchange(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmExchange(arg0);
            return result;
        }
    }
    async createMarketplaceListing(arg0: string, arg1: bigint, arg2: string, arg3: string, arg4: FileMetadata, arg5: string, arg6: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMarketplaceListing(arg0, arg1, arg2, arg3, await to_candid_FileMetadata_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMarketplaceListing(arg0, arg1, arg2, arg3, await to_candid_FileMetadata_n10(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async createMeetup(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createMeetup(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createMeetup(arg0, arg1);
            return result;
        }
    }
    async createRating(arg0: string, arg1: number, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createRating(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createRating(arg0, arg1, to_candid_opt_n13(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createServiceListing(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createServiceListing(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createServiceListing(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deletePaper(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePaper(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePaper(arg0);
            return result;
        }
    }
    async getActiveMarketplaceListings(): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveMarketplaceListings();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveMarketplaceListings();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveServiceListings(): Promise<Array<ServiceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveServiceListings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveServiceListings();
            return result;
        }
    }
    async getAllMarketplaceListingsAdmin(): Promise<Array<MarketplaceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarketplaceListingsAdmin();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarketplaceListingsAdmin();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllServiceListingsAdmin(): Promise<Array<ServiceListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllServiceListingsAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllServiceListingsAdmin();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getListingRatingSummary(arg0: string): Promise<[number, bigint]> {
        if (this.processError) {
            try {
                const result = await this.actor.getListingRatingSummary(arg0);
                return [
                    result[0],
                    result[1]
                ];
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getListingRatingSummary(arg0);
            return [
                result[0],
                result[1]
            ];
        }
    }
    async getMarketplaceListingById(arg0: string): Promise<MarketplaceListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarketplaceListingById(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarketplaceListingById(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeetupStatus(arg0: string): Promise<{
        buyerConfirmed: boolean;
        exchangeConfirmed: boolean;
        sellerConfirmed: boolean;
        meetupNote: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeetupStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeetupStatus(arg0);
            return result;
        }
    }
    async getMyListings(): Promise<{
        marketplace: Array<MarketplaceListing>;
        services: Array<ServiceListing>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_record_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPaper(arg0: string): Promise<Paper | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaper(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaper(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPapers(): Promise<Array<Paper>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPapers();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPapers();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRecentNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentNotifications();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentNotifications();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceListingById(arg0: string): Promise<ServiceListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceListingById(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceListingById(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markAsPurchased(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAsPurchased(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAsPurchased(arg0);
            return result;
        }
    }
    async markNotificationsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead(arg0);
            return result;
        }
    }
    async resetPurchaseStatus(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetPurchaseStatus(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetPurchaseStatus(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async softDeleteMarketplaceListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.softDeleteMarketplaceListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.softDeleteMarketplaceListing(arg0);
            return result;
        }
    }
    async softDeleteServiceListing(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.softDeleteServiceListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.softDeleteServiceListing(arg0);
            return result;
        }
    }
    async updateMarketplaceListing(arg0: string, arg1: ListingUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarketplaceListing(arg0, await to_candid_ListingUpdate_n36(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarketplaceListing(arg0, await to_candid_ListingUpdate_n36(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMyProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMyProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async updateServiceListing(arg0: string, arg1: {
        serviceDescription: string;
        category: string;
        helperWhatsapp: string;
        helperName: string;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceListing(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceListing(arg0, arg1);
            return result;
        }
    }
    async uploadFile(arg0: string, arg1: string, arg2: bigint, arg3: ExternalBlob): Promise<{
        __kind__: "ok";
        ok: FileMetadata;
    } | {
        __kind__: "err";
        err: UploadError;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(arg0, arg1, arg2, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg3));
                return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(arg0, arg1, arg2, await to_candid_ExternalBlob_n12(this._uploadFile, this._downloadFile, arg3));
            return from_candid_variant_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async uploadPaper(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: string, arg5: FileMetadata): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadPaper(arg0, arg1, arg2, arg3, arg4, await to_candid_FileMetadata_n10(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadPaper(arg0, arg1, arg2, arg3, arg4, await to_candid_FileMetadata_n10(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileMetadata_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileMetadata): Promise<FileMetadata> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_ListingType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ListingType): ListingType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_MarketplaceListing_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarketplaceListing): Promise<MarketplaceListing> {
    return await from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_Paper_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Paper): Promise<Paper> {
    return await from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UploadError_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadError): UploadError {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MarketplaceListing]): Promise<MarketplaceListing | null> {
    return value.length === 0 ? null : await from_candid_MarketplaceListing_n15(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Paper]): Promise<Paper | null> {
    return value.length === 0 ? null : await from_candid_Paper_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceListing]): ServiceListing | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    sellerWhatsapp: string;
    active: boolean;
    subject: string;
    listingId: string;
    createdBy: Principal;
    sold: boolean;
    sellerName: string;
    buyerPrincipal: [] | [Principal];
    photo: _FileMetadata;
    price: bigint;
    classYear: string;
}): Promise<{
    id: string;
    title: string;
    sellerWhatsapp: string;
    active: boolean;
    subject: string;
    listingId: string;
    createdBy: Principal;
    sold: boolean;
    sellerName: string;
    buyerPrincipal?: Principal;
    photo: FileMetadata;
    price: bigint;
    classYear: string;
}> {
    return {
        id: value.id,
        title: value.title,
        sellerWhatsapp: value.sellerWhatsapp,
        active: value.active,
        subject: value.subject,
        listingId: value.listingId,
        createdBy: value.createdBy,
        sold: value.sold,
        sellerName: value.sellerName,
        buyerPrincipal: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.buyerPrincipal)),
        photo: await from_candid_FileMetadata_n18(_uploadFile, _downloadFile, value.photo),
        price: value.price,
        classYear: value.classYear
    };
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: bigint;
    fileBlob: _ExternalBlob;
    mimeType: string;
    filename: string;
}): Promise<{
    size: bigint;
    fileBlob: ExternalBlob;
    mimeType: string;
    filename: string;
}> {
    return {
        size: value.size,
        fileBlob: await from_candid_ExternalBlob_n20(_uploadFile, _downloadFile, value.fileBlob),
        mimeType: value.mimeType,
        filename: value.filename
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marketplace: Array<_MarketplaceListing>;
    services: Array<_ServiceListing>;
}): Promise<{
    marketplace: Array<MarketplaceListing>;
    services: Array<ServiceListing>;
}> {
    return {
        marketplace: await from_candid_vec_n14(_uploadFile, _downloadFile, value.marketplace),
        services: value.services
    };
}
async function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    subject: string;
    year: bigint;
    description: string;
    fileMetadata: _FileMetadata;
    uploadedAt: bigint;
    uploadedBy: Principal;
}): Promise<{
    id: string;
    title: string;
    subject: string;
    year: bigint;
    description: string;
    fileMetadata: FileMetadata;
    uploadedAt: bigint;
    uploadedBy: Principal;
}> {
    return {
        id: value.id,
        title: value.title,
        subject: value.subject,
        year: value.year,
        description: value.description,
        fileMetadata: await from_candid_FileMetadata_n18(_uploadFile, _downloadFile, value.fileMetadata),
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    listingId: string;
    listingType: _ListingType;
    message: string;
    timestamp: bigint;
    listingTitle: string;
}): {
    listingId: string;
    listingType: ListingType;
    message: string;
    timestamp: bigint;
    listingTitle: string;
} {
    return {
        listingId: value.listingId,
        listingType: from_candid_ListingType_n33(_uploadFile, _downloadFile, value.listingType),
        message: value.message,
        timestamp: value.timestamp,
        listingTitle: value.listingTitle
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    service: null;
} | {
    marketplace: null;
}): ListingType {
    return "service" in value ? ListingType.service : "marketplace" in value ? ListingType.marketplace : value;
}
async function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _FileMetadata;
} | {
    err: _UploadError;
}): Promise<{
    __kind__: "ok";
    ok: FileMetadata;
} | {
    __kind__: "err";
    err: UploadError;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_FileMetadata_n18(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_UploadError_n39(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fileTooLarge: string;
} | {
    internalError: string;
} | {
    actorUnavailable: string;
} | {
    callerNotAuthenticated: string;
}): {
    __kind__: "fileTooLarge";
    fileTooLarge: string;
} | {
    __kind__: "internalError";
    internalError: string;
} | {
    __kind__: "actorUnavailable";
    actorUnavailable: string;
} | {
    __kind__: "callerNotAuthenticated";
    callerNotAuthenticated: string;
} {
    return "fileTooLarge" in value ? {
        __kind__: "fileTooLarge",
        fileTooLarge: value.fileTooLarge
    } : "internalError" in value ? {
        __kind__: "internalError",
        internalError: value.internalError
    } : "actorUnavailable" in value ? {
        __kind__: "actorUnavailable",
        actorUnavailable: value.actorUnavailable
    } : "callerNotAuthenticated" in value ? {
        __kind__: "callerNotAuthenticated",
        callerNotAuthenticated: value.callerNotAuthenticated
    } : value;
}
async function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MarketplaceListing>): Promise<Array<MarketplaceListing>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MarketplaceListing_n15(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Paper>): Promise<Array<Paper>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Paper_n27(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n31(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FileMetadata_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileMetadata): Promise<_FileMetadata> {
    return await to_candid_record_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_ListingUpdate_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ListingUpdate): Promise<_ListingUpdate> {
    return await to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    size: bigint;
    fileBlob: ExternalBlob;
    mimeType: string;
    filename: string;
}): Promise<{
    size: bigint;
    fileBlob: _ExternalBlob;
    mimeType: string;
    filename: string;
}> {
    return {
        size: value.size,
        fileBlob: await to_candid_ExternalBlob_n12(_uploadFile, _downloadFile, value.fileBlob),
        mimeType: value.mimeType,
        filename: value.filename
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    sellerWhatsapp: string;
    subject: string;
    sellerName: string;
    photo: FileMetadata;
    price: bigint;
    classYear: string;
}): Promise<{
    title: string;
    sellerWhatsapp: string;
    subject: string;
    sellerName: string;
    photo: _FileMetadata;
    price: bigint;
    classYear: string;
}> {
    return {
        title: value.title,
        sellerWhatsapp: value.sellerWhatsapp,
        subject: value.subject,
        sellerName: value.sellerName,
        photo: await to_candid_FileMetadata_n10(_uploadFile, _downloadFile, value.photo),
        price: value.price,
        classYear: value.classYear
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
