/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface FileMetadata {
  'size' : bigint,
  'fileBlob' : ExternalBlob,
  'mimeType' : string,
  'filename' : string,
}
export type ListingType = { 'service' : null } |
  { 'marketplace' : null };
export interface ListingUpdate {
  'title' : string,
  'sellerWhatsapp' : string,
  'subject' : string,
  'sellerName' : string,
  'photo' : FileMetadata,
  'price' : bigint,
  'classYear' : string,
}
export interface MarketplaceListing {
  'id' : string,
  'title' : string,
  'sellerWhatsapp' : string,
  'active' : boolean,
  'subject' : string,
  'listingId' : string,
  'createdBy' : Principal,
  'sold' : boolean,
  'sellerName' : string,
  'buyerPrincipal' : [] | [Principal],
  'photo' : FileMetadata,
  'price' : bigint,
  'classYear' : string,
}
export interface Notification {
  'listingId' : string,
  'listingType' : ListingType,
  'message' : string,
  'timestamp' : bigint,
  'listingTitle' : string,
}
export interface Paper {
  'id' : string,
  'title' : string,
  'subject' : string,
  'year' : bigint,
  'description' : string,
  'fileMetadata' : FileMetadata,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export interface ServiceListing {
  'id' : string,
  'active' : boolean,
  'listingId' : string,
  'createdBy' : Principal,
  'serviceDescription' : string,
  'category' : string,
  'helperWhatsapp' : string,
  'helperName' : string,
}
export type UploadError = { 'fileTooLarge' : string } |
  { 'internalError' : string } |
  { 'actorUnavailable' : string } |
  { 'callerNotAuthenticated' : string };
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'whatsappNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'confirmExchange' : ActorMethod<[string], undefined>,
  'createMarketplaceListing' : ActorMethod<
    [string, bigint, string, string, FileMetadata, string, string],
    undefined
  >,
  'createMeetup' : ActorMethod<[string, string], undefined>,
  'createRating' : ActorMethod<[string, number, [] | [string]], undefined>,
  'createServiceListing' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'deletePaper' : ActorMethod<[string], undefined>,
  'getActiveMarketplaceListings' : ActorMethod<[], Array<MarketplaceListing>>,
  'getActiveServiceListings' : ActorMethod<[], Array<ServiceListing>>,
  'getAllMarketplaceListingsAdmin' : ActorMethod<[], Array<MarketplaceListing>>,
  'getAllServiceListingsAdmin' : ActorMethod<[], Array<ServiceListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getListingRatingSummary' : ActorMethod<[string], [number, bigint]>,
  'getMarketplaceListingById' : ActorMethod<
    [string],
    [] | [MarketplaceListing]
  >,
  'getMeetupStatus' : ActorMethod<
    [string],
    {
      'buyerConfirmed' : boolean,
      'exchangeConfirmed' : boolean,
      'sellerConfirmed' : boolean,
      'meetupNote' : string,
    }
  >,
  'getMyListings' : ActorMethod<
    [],
    {
      'marketplace' : Array<MarketplaceListing>,
      'services' : Array<ServiceListing>,
    }
  >,
  'getPaper' : ActorMethod<[string], [] | [Paper]>,
  'getPapers' : ActorMethod<[], Array<Paper>>,
  'getRecentNotifications' : ActorMethod<[], Array<Notification>>,
  'getServiceListingById' : ActorMethod<[string], [] | [ServiceListing]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsPurchased' : ActorMethod<[string], undefined>,
  'markNotificationsRead' : ActorMethod<[bigint], undefined>,
  'resetPurchaseStatus' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'softDeleteMarketplaceListing' : ActorMethod<[string], undefined>,
  'softDeleteServiceListing' : ActorMethod<[string], undefined>,
  'updateMarketplaceListing' : ActorMethod<[string, ListingUpdate], undefined>,
  'updateMyProfile' : ActorMethod<[string, string, string], undefined>,
  'updateServiceListing' : ActorMethod<
    [
      string,
      {
        'serviceDescription' : string,
        'category' : string,
        'helperWhatsapp' : string,
        'helperName' : string,
      },
    ],
    undefined
  >,
  'uploadFile' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    { 'ok' : FileMetadata } |
      { 'err' : UploadError }
  >,
  'uploadPaper' : ActorMethod<
    [string, string, string, bigint, string, FileMetadata],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];