/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileMetadata = IDL.Record({
  'size' : IDL.Nat,
  'fileBlob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const MarketplaceListing = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'sellerWhatsapp' : IDL.Text,
  'active' : IDL.Bool,
  'subject' : IDL.Text,
  'listingId' : IDL.Text,
  'createdBy' : IDL.Principal,
  'sold' : IDL.Bool,
  'sellerName' : IDL.Text,
  'buyerPrincipal' : IDL.Opt(IDL.Principal),
  'photo' : FileMetadata,
  'price' : IDL.Nat,
  'classYear' : IDL.Text,
});
export const ServiceListing = IDL.Record({
  'id' : IDL.Text,
  'active' : IDL.Bool,
  'listingId' : IDL.Text,
  'createdBy' : IDL.Principal,
  'serviceDescription' : IDL.Text,
  'category' : IDL.Text,
  'helperWhatsapp' : IDL.Text,
  'helperName' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'whatsappNumber' : IDL.Text,
});
export const Paper = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'subject' : IDL.Text,
  'year' : IDL.Nat,
  'description' : IDL.Text,
  'fileMetadata' : FileMetadata,
  'uploadedAt' : IDL.Int,
  'uploadedBy' : IDL.Principal,
});
export const ListingType = IDL.Variant({
  'service' : IDL.Null,
  'marketplace' : IDL.Null,
});
export const Notification = IDL.Record({
  'listingId' : IDL.Text,
  'listingType' : ListingType,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
  'listingTitle' : IDL.Text,
});
export const ListingUpdate = IDL.Record({
  'title' : IDL.Text,
  'sellerWhatsapp' : IDL.Text,
  'subject' : IDL.Text,
  'sellerName' : IDL.Text,
  'photo' : FileMetadata,
  'price' : IDL.Nat,
  'classYear' : IDL.Text,
});
export const UploadError = IDL.Variant({
  'fileTooLarge' : IDL.Text,
  'internalError' : IDL.Text,
  'actorUnavailable' : IDL.Text,
  'callerNotAuthenticated' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'confirmExchange' : IDL.Func([IDL.Text], [], []),
  'createMarketplaceListing' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, FileMetadata, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createMeetup' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createRating' : IDL.Func([IDL.Text, IDL.Nat8, IDL.Opt(IDL.Text)], [], []),
  'createServiceListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deletePaper' : IDL.Func([IDL.Text], [], []),
  'getActiveMarketplaceListings' : IDL.Func(
      [],
      [IDL.Vec(MarketplaceListing)],
      ['query'],
    ),
  'getActiveServiceListings' : IDL.Func(
      [],
      [IDL.Vec(ServiceListing)],
      ['query'],
    ),
  'getAllMarketplaceListingsAdmin' : IDL.Func(
      [],
      [IDL.Vec(MarketplaceListing)],
      ['query'],
    ),
  'getAllServiceListingsAdmin' : IDL.Func(
      [],
      [IDL.Vec(ServiceListing)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getListingRatingSummary' : IDL.Func(
      [IDL.Text],
      [IDL.Float64, IDL.Nat],
      ['query'],
    ),
  'getMarketplaceListingById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MarketplaceListing)],
      ['query'],
    ),
  'getMeetupStatus' : IDL.Func(
      [IDL.Text],
      [
        IDL.Record({
          'buyerConfirmed' : IDL.Bool,
          'exchangeConfirmed' : IDL.Bool,
          'sellerConfirmed' : IDL.Bool,
          'meetupNote' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getMyListings' : IDL.Func(
      [],
      [
        IDL.Record({
          'marketplace' : IDL.Vec(MarketplaceListing),
          'services' : IDL.Vec(ServiceListing),
        }),
      ],
      ['query'],
    ),
  'getPaper' : IDL.Func([IDL.Text], [IDL.Opt(Paper)], ['query']),
  'getPapers' : IDL.Func([], [IDL.Vec(Paper)], ['query']),
  'getRecentNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getServiceListingById' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ServiceListing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsPurchased' : IDL.Func([IDL.Text], [], []),
  'markNotificationsRead' : IDL.Func([IDL.Int], [], []),
  'resetPurchaseStatus' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'softDeleteMarketplaceListing' : IDL.Func([IDL.Text], [], []),
  'softDeleteServiceListing' : IDL.Func([IDL.Text], [], []),
  'updateMarketplaceListing' : IDL.Func([IDL.Text, ListingUpdate], [], []),
  'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateServiceListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Record({
          'serviceDescription' : IDL.Text,
          'category' : IDL.Text,
          'helperWhatsapp' : IDL.Text,
          'helperName' : IDL.Text,
        }),
      ],
      [],
      [],
    ),
  'uploadFile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
      [IDL.Variant({ 'ok' : FileMetadata, 'err' : UploadError })],
      [],
    ),
  'uploadPaper' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, FileMetadata],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileMetadata = IDL.Record({
    'size' : IDL.Nat,
    'fileBlob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const MarketplaceListing = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'sellerWhatsapp' : IDL.Text,
    'active' : IDL.Bool,
    'subject' : IDL.Text,
    'listingId' : IDL.Text,
    'createdBy' : IDL.Principal,
    'sold' : IDL.Bool,
    'sellerName' : IDL.Text,
    'buyerPrincipal' : IDL.Opt(IDL.Principal),
    'photo' : FileMetadata,
    'price' : IDL.Nat,
    'classYear' : IDL.Text,
  });
  const ServiceListing = IDL.Record({
    'id' : IDL.Text,
    'active' : IDL.Bool,
    'listingId' : IDL.Text,
    'createdBy' : IDL.Principal,
    'serviceDescription' : IDL.Text,
    'category' : IDL.Text,
    'helperWhatsapp' : IDL.Text,
    'helperName' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'whatsappNumber' : IDL.Text,
  });
  const Paper = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'subject' : IDL.Text,
    'year' : IDL.Nat,
    'description' : IDL.Text,
    'fileMetadata' : FileMetadata,
    'uploadedAt' : IDL.Int,
    'uploadedBy' : IDL.Principal,
  });
  const ListingType = IDL.Variant({
    'service' : IDL.Null,
    'marketplace' : IDL.Null,
  });
  const Notification = IDL.Record({
    'listingId' : IDL.Text,
    'listingType' : ListingType,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
    'listingTitle' : IDL.Text,
  });
  const ListingUpdate = IDL.Record({
    'title' : IDL.Text,
    'sellerWhatsapp' : IDL.Text,
    'subject' : IDL.Text,
    'sellerName' : IDL.Text,
    'photo' : FileMetadata,
    'price' : IDL.Nat,
    'classYear' : IDL.Text,
  });
  const UploadError = IDL.Variant({
    'fileTooLarge' : IDL.Text,
    'internalError' : IDL.Text,
    'actorUnavailable' : IDL.Text,
    'callerNotAuthenticated' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'confirmExchange' : IDL.Func([IDL.Text], [], []),
    'createMarketplaceListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          FileMetadata,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'createMeetup' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createRating' : IDL.Func([IDL.Text, IDL.Nat8, IDL.Opt(IDL.Text)], [], []),
    'createServiceListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deletePaper' : IDL.Func([IDL.Text], [], []),
    'getActiveMarketplaceListings' : IDL.Func(
        [],
        [IDL.Vec(MarketplaceListing)],
        ['query'],
      ),
    'getActiveServiceListings' : IDL.Func(
        [],
        [IDL.Vec(ServiceListing)],
        ['query'],
      ),
    'getAllMarketplaceListingsAdmin' : IDL.Func(
        [],
        [IDL.Vec(MarketplaceListing)],
        ['query'],
      ),
    'getAllServiceListingsAdmin' : IDL.Func(
        [],
        [IDL.Vec(ServiceListing)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getListingRatingSummary' : IDL.Func(
        [IDL.Text],
        [IDL.Float64, IDL.Nat],
        ['query'],
      ),
    'getMarketplaceListingById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MarketplaceListing)],
        ['query'],
      ),
    'getMeetupStatus' : IDL.Func(
        [IDL.Text],
        [
          IDL.Record({
            'buyerConfirmed' : IDL.Bool,
            'exchangeConfirmed' : IDL.Bool,
            'sellerConfirmed' : IDL.Bool,
            'meetupNote' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getMyListings' : IDL.Func(
        [],
        [
          IDL.Record({
            'marketplace' : IDL.Vec(MarketplaceListing),
            'services' : IDL.Vec(ServiceListing),
          }),
        ],
        ['query'],
      ),
    'getPaper' : IDL.Func([IDL.Text], [IDL.Opt(Paper)], ['query']),
    'getPapers' : IDL.Func([], [IDL.Vec(Paper)], ['query']),
    'getRecentNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getServiceListingById' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ServiceListing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsPurchased' : IDL.Func([IDL.Text], [], []),
    'markNotificationsRead' : IDL.Func([IDL.Int], [], []),
    'resetPurchaseStatus' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'softDeleteMarketplaceListing' : IDL.Func([IDL.Text], [], []),
    'softDeleteServiceListing' : IDL.Func([IDL.Text], [], []),
    'updateMarketplaceListing' : IDL.Func([IDL.Text, ListingUpdate], [], []),
    'updateMyProfile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateServiceListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Record({
            'serviceDescription' : IDL.Text,
            'category' : IDL.Text,
            'helperWhatsapp' : IDL.Text,
            'helperName' : IDL.Text,
          }),
        ],
        [],
        [],
      ),
    'uploadFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, ExternalBlob],
        [IDL.Variant({ 'ok' : FileMetadata, 'err' : UploadError })],
        [],
      ),
    'uploadPaper' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, FileMetadata],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };